package regex

import (
	"fmt"
	"regexp/syntax"
	"strings"
)

// AST returns a readable syntax tree generated by the standard parser.
func AST(pattern string) (string, *Error) {
	re, err := syntax.Parse(pattern, syntax.Perl)
	if err != nil {
		return "", compileError(err)
	}
	var b strings.Builder
	var walk func(*syntax.Regexp, string)
	walk = func(n *syntax.Regexp, prefix string) {
		b.WriteString(prefix + n.Op.String())
		if n.Name != "" {
			b.WriteString("<" + n.Name + ">")
		}
		if n.Rune != nil {
			b.WriteString(fmt.Sprintf(" %q", string(n.Rune)))
		}
		b.WriteByte('\n')
		for _, s := range n.Sub {
			walk(s, prefix+"  ")
		}
	}
	walk(re, "")
	return b.String(), nil
}
